from SCons import SConsign
import os

# By default, SCons resets all environment variables. This means that
# instead of compiling against the library versions you chose, it will
# build against whatever happens to be the default on the system today.
# It also breaks when plash is used.
# This makes the current environment available to the build:
env = Environment(ENV = os.environ)
Export('env')

srcdir = os.environ['SRCDIR']
builddir = os.environ['BUILDDIR']
distdir = os.environ['DISTDIR']
javasrc = os.path.join(srcdir, 'src', 'main', 'java')

env.Java(builddir, javasrc)
env.Jar(target = os.path.join(distdir, 'hello.jar'),
	source = [builddir, os.path.join(javasrc, 'Manifest.txt')])
